// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'intro',
    'starting code',
    {
      type: 'category',
      label: 'Commands Implementation',
      items: [
        'Commands Implementation/init command',
        'Commands Implementation/hash-object command',
        'Commands Implementation/cat-file command',
        'Commands Implementation/add command',
        'Commands Implementation/ls-files command',
        'Commands Implementation/write-tree command',
        'Commands Implementation/ls-tree command',
        'Commands Implementation/commit command',
        'Commands Implementation/log command',
      ]
      
    },
    'final',
  ],

};

export default sidebars;
